#!/usr/bin/env python3
"""Regenerate the FortiGuard / Application category locals from the live FortiSASE API.

Instead of maintaining ~90 FortiGuard categories and ~22 application categories by
hand, this script fetches the current list on the fly and rewrites:

    modules/security/locals-categories_fgd.tf
    modules/security/locals-categories_app.tf

The generated structure is identical to the hand-written one: every category is set
to "monitor", a small default-block set (unsecure categories) is forced to "block",
and the `*_restricted_categories` Terraform variables still flip extra categories to
"block" at plan time. New categories Fortinet adds simply appear as "monitor".

Auth reuses the same flow as api/delete_all.py (FortiSASE API user credentials):

    export TF_VAR_username=...    # FortiSASE API user
    export TF_VAR_password=...
    python util/generate_categories.py            # writes into modules/security/
    python util/generate_categories.py --stdout   # print, don't write (dry run)
"""

import argparse
import logging
import os
import sys
from pathlib import Path

import requests

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

OAUTH_URL = "https://customerapiauth.fortinet.com/api/v1/oauth/token/"
BASE_URL = "https://portal.prod.fortisase.com"
TIMEOUT = 180

FGD_RESOURCE = "/resource-api/v2/security/fortiguard-categories"
APP_RESOURCE = "/resource-api/v2/security/application-categories"

# Categories blocked by default (considered unsecure). Everything else is "monitor".
# Mirrors the original hand-written locals; review when Fortinet adds new categories.
DEFAULT_BLOCK_FGD = {
    "Terrorism",
    "Crypto Mining",
    "Potentially Unwanted Program",
    "Malicious Websites",
    "Phishing",
    "Spam URLs",
    "Dynamic DNS",
    "Newly Observed Domain",
    "Newly Registered Domain",
}
DEFAULT_BLOCK_APP = set()


def obtain_token() -> str:
    username = os.getenv("TF_VAR_username")
    password = os.getenv("TF_VAR_password")
    if not username or not password:
        logging.error("Need TF_VAR_username and TF_VAR_password (FortiSASE API user).")
        sys.exit(2)

    logging.info("** Requesting API token")
    payload = {
        "username": username,
        "password": password,
        "client_id": "FortiSASE",
        "client_secret": "",
        "grant_type": "password",
    }
    try:
        resp = requests.post(OAUTH_URL, json=payload, timeout=TIMEOUT)
    except requests.RequestException as e:
        logging.error(f"   Request failed: {e}")
        sys.exit(2)
    if not 200 <= resp.status_code < 300:
        logging.error(f"   Could not obtain token (HTTP {resp.status_code}): {resp.text}")
        sys.exit(1)
    logging.info("   Token received")
    return "Bearer " + resp.json()["access_token"]


def fetch_primary_keys(token: str, resource: str, name: str) -> list[str]:
    logging.info(f"** Fetching {name}")
    try:
        resp = requests.get(BASE_URL + resource, headers={"Authorization": token}, timeout=TIMEOUT)
    except requests.RequestException as e:
        logging.error(f"   Request failed: {e}")
        sys.exit(2)
    if not 200 <= resp.status_code < 300:
        logging.error(f"   HTTP {resp.status_code} fetching {resource}: {resp.text}")
        sys.exit(1)
    keys = [item["primaryKey"] for item in resp.json().get("data", [])]
    logging.info(f"   Found {len(keys)} {name}")
    if not keys:
        logging.error(f"   No categories returned for {name}; aborting to avoid wiping the file.")
        sys.exit(1)
    return sorted(keys)


def render_fgd(keys: list[str]) -> str:
    # The dangerous default-block set must ALWAYS be present and blocked, even if the
    # API ever stops returning one of those categories.
    missing = DEFAULT_BLOCK_FGD - set(keys)
    if missing:
        logging.warning(f"   Default-block categories not returned by API, forcing them in: {sorted(missing)}")
    keys = sorted(set(keys) | DEFAULT_BLOCK_FGD)
    entries = []
    for key in keys:
        action = "block" if key in DEFAULT_BLOCK_FGD else "monitor"
        entries.append(
            f'''    {{
      action = "{action}",
      category = {{
        datasource  = "security/fortiguard-categories",
        primary_key = "{key}"
      }},
      warning_duration = null
    }}'''
        )
    body = ",\n".join(entries)
    return f'''# GENERATED by util/generate_categories.py -- do not edit by hand.
locals {{

  # Set fgd restricted categories to block
  fgd_restricted_categories = [
    for category in local.fgd_categories_all_monitor : (
      contains(var.webfilter_restricted_categories, category.category.primary_key)
      ? merge(category, {{ action = "block" }})
      : category
    )
  ]

  # All fgd categories are set to monitor,
  # except the ones blocked by default, considered unsecure:
  # "Malicious Websites", "Phishing", etc.
  fgd_categories_all_monitor = [
{body}
  ]
}}
'''


def render_app(keys: list[str]) -> str:
    keys = sorted(set(keys) | DEFAULT_BLOCK_APP)
    entries = []
    for key in keys:
        action = "block" if key in DEFAULT_BLOCK_APP else "monitor"
        entries.append(
            f'''    {{
      action = "{action}",
      category = {{
        datasource  = "security/application-categories",
        primary_key = "{key}"
      }}
    }}'''
        )
    body = ",\n".join(entries)
    return f'''# GENERATED by util/generate_categories.py -- do not edit by hand.
locals {{

  # Set app restricted categories to block
  app_restricted_categories = [
    for category in local.app_categories_all_monitor : (
      contains(var.app_restricted_categories, category.category.primary_key)
      ? merge(category, {{ action = "block" }})
      : category
    )
  ]

  # All app categories are set to monitor
  app_categories_all_monitor = [
{body}
  ]
}}
'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out-dir",
        default=str(Path(__file__).resolve().parent.parent / "modules" / "security"),
        help="Directory to write the generated .tf files into.",
    )
    parser.add_argument("--stdout", action="store_true", help="Print instead of writing files.")
    args = parser.parse_args()

    token = obtain_token()
    fgd = render_fgd(fetch_primary_keys(token, FGD_RESOURCE, "FortiGuard categories"))
    app = render_app(fetch_primary_keys(token, APP_RESOURCE, "application categories"))

    if args.stdout:
        print(fgd)
        print(app)
        return

    out = Path(args.out_dir)
    (out / "locals-categories_fgd.tf").write_text(fgd)
    (out / "locals-categories_app.tf").write_text(app)
    logging.info(f"** Wrote locals-categories_fgd.tf and locals-categories_app.tf into {out}")


if __name__ == "__main__":
    main()
